### PR TITLE
update Baidu voice pic

### PR DESCRIPTION
**Pull request by maxwell92**
fixed the invalid link of Baidu Voice Service Pic

### CODE REVIEW

**Comment by chenqinghe** [comment]
perhaps the screenshot of this page is better: http://ai.baidu.com/. on this site, all the services are concentrated here, users can create application with needed services in console conveniently.

**Comment by maxwell92** [comment]
Yes, you are right. how about this one ? 
image

**Comment by chenqinghe** [comment]
pretty good! is i edit directly, or you create a new PR?

**Comment by maxwell92** [comment]
I will raise a new PR

**Pull request closed without merging**
